---
title: "PR5"
author: "PR5_201821479_황혜린"
date: "2018년 10월 11일"
output: word_document
---

# 조건문과 반복문
## 1. 반복문 
### 1.1 for()
```{r}
a<-c(1,2,4) ; a

for(i in a) print(i)
for(i in c(1,2,4))
  print(i)
string=c("test","for","for()")
for(i in string)
  print(i)
for(i in c("test","for","for()"))
  print(i)
for(i in 1:3)
  print(i)
print("다음줄")
print(i+1)

for(i in 1:3){
  print(i)
  print("다음줄")
  print(i+1)
}

j<-1:6
for(i in seq(2,6,by=2)){
  print(paste0(i,"번째 데이터:"))
  print(j[i])
}

for(a in 1:10)
  print(a)

for(i in 1:10){
  print(i)
  break
}
```

### 1.2 while()문   
```{r}
i=1
while(i<5){
  print(i)
  i=i+1
}
```

### 1.3 repeat
```{r}
i<-1
repeat{
  i<-i+30
  if(i>100)break
  print(i)
}
```

# 2. 조건문 
## 2.1 if문과 if-else문 
```{r}
x=80
if(x<=90) print("B")
if(x<=80) print("C")

x<-91
if(x>90){
  print("B")
  x=x+10
  print(x)
}

x<-91
if(x<=90) print("B") else print("C")

if(x<90){
  print("B")
  x=x+10
}else{
  print("C")
}

x<-100
if(x<70){
  print("F")
}else if(x<80) {
  print("C")
}else if(x<90) {
  print("B")
}else {
  print("A")
}
```

## 2.2 ifelse
```{r}
x=10
ifelse(x>5,x+5,x-5)
```

# 3. 조건문과 반복문 함께 사용하기 
```{r}
x<-1:10
for(i in x){
  if(i%%2==0){
    print(i)
  }  
}
```

# 연습문제
## 문제1
```{r}
vec <- NULL  #vec에 NULL할당 
for(i in (1:100)){

  vec<- append(vec, paste0("https://movie.daum.net/moviedb/grade?movieId=95554&type=netizen&page=",i))  
}         #paste0를 통해 링크에 1,2,3..숫자를 부여하고, vec에 append를 사용해 원소(링크)를 1~100까지 대응시킵니다    
print(vec) #vec출력!
```
## 문제2
```{r}
for (x in 2) {
  for (y in 1:9) {
    print(paste(x,"*",y,"=",x*y))
  }
}
#x에 2, y에 1~9 를 넣고 수식을 만들고 paste!
```
## 문제3- 1
```{r}
a<-0
for(i in 1:1000){    
  if(i%%10==3){   #일의 자리 수 이상의 3이 들어가는 수
    a<-a+1}        
  if((i%/%10)%%10==3){  #십의 자리 수 이상의 3이 들어가는 수
    a<-a+1}
  if((i%/%100)%%10==3){   #백의 자리 수 이상의 3이 들어가는 수
    a<-a+1}
 
}
print(a) #3이 들어있는 수가 세어져 축적된 a값 출력

```